controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

    # index:
    #  path: /blog
    #  contotroller: App/Controller\BlogController::index
